### PR TITLE
Removes buffered event channel, and adds dynamic slice event buffer

### PR DESCRIPTION
**Pull request by tomponline**
removes buffered event channel, and adds a dynamic slice to buffer events.

Still a work in progress.

Addresses https://github.com/tomponline/fsclient/issues/6

Warning: This introduces a breaking API change in the new client function.

CC @gha

### CODE REVIEW

**Comment by gha** [comment]
Could we also push the command responses to the front of the event buffer?

**Comment by tomponline** [comment]
@gha we shouldnt need to, as they are plucked out in https://github.com/tomponline/fsclient/blob/7fa9ab03cdf6a376b108aae536f659ad4f430380/fsclient/fsclient.go#L318 and are handled separately, this change just ensures that if the client is not able to receive events (perhaps because its waiting for an API response), then we don't delay processing other messages from freeswitch (that might also be the API response), causing a deadlock.

**Comment by tomponline** [comment]
@gha this change basically ensures that https://github.com/tomponline/fsclient/blob/7fa9ab03cdf6a376b108aae536f659ad4f430380/fsclient/fsclient.go#L314 will never be delayed by the user application.

**Review by gha — APPROVED** [review]
lgtm @tomponline

**Comment by tomponline** [comment]
@gha merged, thanks

**Pull request merged**
